In [1]:
import numpy as np

In [4]:
# inputs
def inputs(m, n=None):
  if n:
    return np.random.randint(2, 5, (m, n)).astype(float)
  
  return np.random.randint(2, 5, (m,)).astype(float)
  

In [5]:
X = inputs(10, 3)
X

array([[3., 2., 4.],
       [4., 3., 2.],
       [3., 2., 3.],
       [2., 4., 4.],
       [4., 4., 4.],
       [4., 3., 2.],
       [4., 2., 3.],
       [4., 4., 3.],
       [2., 4., 4.],
       [2., 3., 3.]])

In [7]:
W = inputs(10)
W

array([4., 2., 2., 3., 4., 4., 2., 3., 3., 2.])

In [10]:
# z
def Z(m, n, k):
  b = np.random.randint(10)
  return inputs(m, n) @ inputs(n, k) + b

In [11]:
z = Z(10, 3, 3)
z

array([[41., 42., 33.],
       [38., 38., 30.],
       [42., 40., 31.],
       [37., 37., 29.],
       [46., 44., 34.],
       [49., 48., 37.],
       [40., 42., 33.],
       [44., 44., 34.],
       [34., 33., 26.],
       [38., 38., 30.]])

In [12]:
# sigmoid
def sigmoid(m,n,k):
  return 1 / (1 + np.exp(-Z(m,n,k)))

In [14]:
sig = sigmoid(10,3,3)
sig

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])