In [1]:
!pip install nnfs --quiet

In [2]:
import numpy as np
import nnfs

In [3]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    # initialize weights and biases
    self.weights = np.random.randn(n_inputs, n_neurons) * .01
    self.biases = np.zeros((1, n_neurons))
  
  # forward
  def forward(self, inputs):
    # calculate output values from inputs, weights and biases
    self.output = np.dot(inputs, self.weights) + self.biases


In [4]:
from nnfs.datasets import spiral_data

# Create dataset
X, y = spiral_data(samples=100, classes=3)

In [5]:
# Create Dense layer with 2 input features and 3 output values
dense_1 = Layer_Dense(2, 3)

In [6]:
# Perform a forward pass of our training data through this layer
dense_1.forward(X)

In [7]:
print(dense_1.output[:5])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.45865529e-05  3.04041836e-05  2.83764363e-05]
 [ 1.07105200e-04 -7.75101361e-05 -4.00159858e-04]
 [-2.44462297e-05  1.30358498e-05 -2.54153468e-04]
 [-1.47192023e-05  4.72066181e-06 -3.85182161e-04]]
